# Trova la Moneta Falsa

In un numpy array di n elementi (2 < n < 240) ci sono tutte monete di un certo peso ed una leggermente più pesante. Dovete scoprire quale è l'indice della moneta più pesante!
Per farlo dovete costruire una funzione TEST che dati due array confronti le loro somme e restituisca:
- 1 se il primo è più pesante
- 2 se il secondo è più pesante
- 0 se hanno lo stesso peso

Questa funzione è l'unico modo in cui potete accedere agli elementi dell'array ed il vostro obiettivo è scoprire la moneta falsa in meno TEST possibili.

Il programma dovrà generare nel main una serie di numpy array di varie dimensione e ogni elemento inizializzato ad un numero casuale tra 10000 e 20000 e successivamente scgeliere un indice casuale e aggiungere 1 a quell'elemento.
Create poi una matrice contenente:
- Numero di elementi dell'i-esimo array
- Indice della moneta più pesante dell'i-esimo array
- Indice restituito dal vostro algoritmo dell'i-esimo array
- Numero di volte in cui avete usato TEST per l'i-esimo array

La valutazione terrà conto dell'ottimalità e dell'esattezza della soluzione in primo luogo, successivamente dello stile e chiarezza del codice.
Non è ammesso l'utilizzo di liste, tuple o simili, ma solo di array di numpy.
Buon lavoro!

EXTRA BONUS: fatelo nel caso in cui non sapete se la moneta falsa è più pesante o leggera

In [97]:
import numpy as np


In [98]:
def test(a1,a2):
    s1=sum(a1)
    s2=sum(a2)
    return (s1 > s2) + 2 * (s1 < s2)

In [137]:
n=50
matrix = np.zeros((n, 4))

for p in range(n):
    
    #Estrazione dei parametri
    size = np.random.randint(3,240)
    value = np.random.randint(10000,20001)
    index = np.random.randint(0,size)
    
    #Costruzione dei vettori e della matrice
    coins = value * np.ones(size)
    coins[index] += 1
    matrix[p][0] = size
    matrix[p][1] = index
    
    #Inizializzazione di valiabili che serviranno dopo
    copy = coins
    lun = len(copy)
    count = 0
    global_lb_index = 0
    global_ub_index = 0
    sporadic_group = 0
    
    #Controllo delle monete, verifico la divisibilità della dimensione rispetto a 3 e 2. In teoria nel caso lun=15*2^n  
    #converrebbe dividere per 2. Con n>1 sono tutti pari, l'unica eccezione è lun=15 (n=0) 
    #ma aggiungere un if solo per quello non mi sembrava il caso
    while lun > 1:
        #Parametri per lo split degli array (i più generali)
        med = lun//2
        division = med
        
        if lun % 3 == 0: 
            #Parametri per lo split degli array (specifici per il caso 'divisibile per 3')
            ter = lun//3
            division = ter
            v = np.zeros((3, len(copy[:ter])))
            v[0] = copy[:ter]
            v[1] = copy[ter:2*ter]
            v[2] = copy[2*ter:]
            i = test(v[1],v[2])
            copy = v[i]            
        elif lun % 2 == 0:          
            v = np.zeros((2, len(copy[:med])))
            v[0] = copy[:med]
            v[1] = copy[med:]
            i = test(v[0],v[1]) - 1
            copy = v[i]           
        else:      
            v = np.zeros((2, len(copy[:med])))
            v[0] = copy[:med]
            v[1] = copy[med:-1]
            i = test(v[0],v[1]) - 1         
            #Caso in cui la fake coin è quella lasciata fuori da sola
            if i == -1: 
                division = 0
                sporadic_group = lun - 1
                copy = np.array([copy[-1]])   
            else:
                copy = v[i]
        #Calcolo gli estremi locali (quelli del sottovettore) degli indici dell'aarray contenente la fake coin
        local_ub_index = (i+1) * division - 1 
        local_lb_index = i * division
        
        #Calcolo gli estremi globali (quelli del vettore originale)
        global_lb_index = global_lb_index + local_lb_index + sporadic_group
        global_ub_index = global_lb_index + local_ub_index + sporadic_group
        
        count += 1
        lun = len(copy)
        
    matrix[p][2] = global_lb_index
    matrix[p][3] = count
print(matrix)

Wall time: 0 ns
[[219. 139. 139.   6.]
 [ 72.  68.  68.   5.]
 [131.  86.  86.   7.]
 ...
 [218.  99.  99.   6.]
 [ 68.  27.  27.   6.]
 [ 99.  90.  90.   5.]]


In [117]:
size

14

In [119]:
len(np.ones(size))

14