# Trova la Moneta Falsa

In un numpy array di n elementi (2 < n < 240) ci sono tutte monete di un certo peso ed una leggermente più pesante. Dovete scoprire quale è l'indice della moneta più pesante!
Per farlo dovete costruire una funzione TEST che dati due array confronti le loro somme e restituisca:
- 1 se il primo è più pesante
- 2 se il secondo è più pesante
- 0 se hanno lo stesso peso

Questa funzione è l'unico modo in cui potete accedere agli elementi dell'array ed il vostro obiettivo è scoprire la moneta falsa in meno TEST possibili.

Il programma dovrà generare nel main una serie di numpy array di varie dimensione e ogni elemento inizializzato ad un numero casuale tra 10000 e 20000 e successivamente scegliere un indice casuale e aggiungere 1 a quell'elemento.
Create poi una matrice contenente:
- Numero di elementi dell'i-esimo array
- Indice della moneta più pesante dell'i-esimo array
- Indice restituito dal vostro algoritmo dell'i-esimo array
- Numero di volte in cui avete usato TEST per l'i-esimo array

La valutazione terrà conto dell'ottimalità e dell'esattezza della soluzione in primo luogo, successivamente dello stile e chiarezza del codice.
Non è ammesso l'utilizzo di liste, tuple o simili, ma solo di array di numpy.
Buon lavoro!

EXTRA BONUS: fatelo nel caso in cui non sapete se la moneta falsa è più pesante o leggera

In [2]:
import numpy as np

In [3]:
def TEST(vect_1,vect_2):
    sum_1 = sum(vect_1)
    sum_2 = sum(vect_2)
    if sum_1 > sum_2:
        return 1
    elif sum_1 = sum_2:
        return 0
    else:
        return 2

In [4]:
def search(a,it):
    n = len(a)
    if n == 1:
        arr = np.array([a,it],dtype=object)
        return arr
    third_a = np.array_split(a,3)
    if n%3 == 2 or n%3 == 0:
        big = TEST(third_a[0],third_a[1])
        it +=1
        return search(third_a[big-1],it)
    elif n%3 == 1:
        big = TEST(third_a[1],third_a[2])
        it +=1
        return search(third_a[big],it)

In [7]:
#main()
np.random.seed(45)
A = np.full((237,4),0)
for n in range(3,240):
    val = np.random.randint(10000, 200001)
    arr = np.ones((n,))
    index = np.random.randint(0,n)
    arr[index] = arr[index] + 1
    coin = search(arr,0)
    my_index = np.where(arr == coin[0])
    A[n-3][0] = n
    A[n-3][1] = index
    A[n-3][2] = my_index[0]
    A[n-3][3] = coin[1]
print(A)

[[  3   0   0   1]
 [  4   3   3   1]
 [  5   3   3   2]
 [  6   1   1   2]
 [  7   1   1   2]
 [  8   1   1   2]
 [  9   7   7   2]
 [ 10   8   8   2]
 [ 11   2   2   2]
 [ 12   8   8   3]
 [ 13   1   1   3]
 [ 14   4   4   2]
 [ 15   8   8   3]
 [ 16  10  10   2]
 [ 17   4   4   3]
 [ 18  15  15   3]
 [ 19   6   6   3]
 [ 20  10  10   3]
 [ 21   8   8   3]
 [ 22  17  17   3]
 [ 23  11  11   3]
 [ 24  10  10   3]
 [ 25  16  16   3]
 [ 26  25  25   3]
 [ 27  15  15   3]
 [ 28   2   2   3]
 [ 29  27  27   3]
 [ 30  16  16   3]
 [ 31  18  18   3]
 [ 32   9   9   3]
 [ 33  32  32   3]
 [ 34   6   6   3]
 [ 35  16  16   4]
 [ 36  28  28   4]
 [ 37  24  24   3]
 [ 38  17  17   3]
 [ 39  15  15   4]
 [ 40  19  19   4]
 [ 41  14  14   4]
 [ 42  20  20   4]
 [ 43   9   9   3]
 [ 44  27  27   4]
 [ 45  42  42   4]
 [ 46   7   7   4]
 [ 47  14  14   4]
 [ 48  37  37   4]
 [ 49  11  11   4]
 [ 50  41  41   4]
 [ 51   6   6   4]
 [ 52  39  39   4]
 [ 53  27  27   4]
 [ 54  47  47   4]
 [ 55  29  2