# Trova la Moneta Falsa

In un numpy array di n elementi (2 < n < 240) ci sono tutte monete di un certo peso ed una leggermente più pesante. Dovete scoprire quale è l'indice della moneta più pesante!
Per farlo dovete costruire una funzione TEST che dati due array confronti le loro somme e restituisca:
- 1 se il primo è più pesante
- 2 se il secondo è più pesante
- 0 se hanno lo stesso peso

Questa funzione è l'unico modo in cui potete accedere agli elementi dell'array ed il vostro obiettivo è scoprire la moneta falsa in meno TEST possibili.

Il programma dovrà generare nel main una serie di numpy array di varie dimensione e ogni elemento inizializzato ad un numero casuale tra 10000 e 20000 e successivamente scgeliere un indice casuale e aggiungere 1 a quell'elemento.
Create poi una matrice contenente:
- Numero di elementi dell'i-esimo array
- Indice della moneta più pesante dell'i-esimo array
- Indice restituito dal vostro algoritmo dell'i-esimo array
- Numero di volte in cui avete usato TEST per l'i-esimo array

La valutazione terrà conto dell'ottimalità e dell'esattezza della soluzione in primo luogo, successivamente dello stile e chiarezza del codice.
Non è ammesso l'utilizzo di liste, tuple o simili, ma solo di array di numpy.
Buon lavoro!

EXTRA BONUS: fatelo nel caso in cui non sapete se la moneta falsa è più pesante o leggera

In [22]:
import numpy as np
import random

def TEST(array1, array2):
    if np.sum(array1)>np.sum(array2):
        return 1
    elif np.sum(array1)<np.sum(array2):
        return 2
    else:
        return 0

def find_number(array):
    len=int(array.size)
    meta=len/2
    if len%2!=0:
        half=int(meta-0.5)
        if len==1:
            return array[0], 0 #quando abbiamo lunghezza 0 non abbiamo bisogno di chiamare TEST
        if TEST(array[0:half], array[(half+1):len])==0:
            return array[half], 0 #non c'è bisogno di chiamare TEST
        elif TEST(array[0:half], array[(half+1):len])==1:
            return find_number(array[0:half])[0], 1+find_number(array[0:half])[1]
        else:
            return find_number(array[(half+1):len])[0], 1+find_number(array[(half+1):len])[1]
    else:
        meta=int(meta)
        if TEST(array[0:meta], array[meta:len])==1:
            return find_number(array[0:meta])[0], 1+find_number(array[0:meta])[1]
        else:
            return find_number(array[meta:len])[0], 1+find_number(array[meta:len])[1]

def find_index(array):
    return (np.where(array==find_number(array)[0]))[0][0], find_number(array)[1]

np.random.seed(42)
n=5
matrix=np.zeros((n,4))
for i in range(n):
    array=np.ones(random.randint(2,240))*random.randint(10000, 20000)
    ind=random.randint(0, array.size-1)
    array[ind]=array[ind]+1
    matrix[i, 0]=array.size
    matrix[i, 1]=ind
    matrix[i, 2]=(find_index(array))[0]
    matrix[i, 3]=(find_index(array))[1]

print(matrix)



[[172.  24.  24.   5.]
 [ 48.  45.  45.   5.]
 [197. 102. 102.   7.]
 [103.  10.  10.   5.]
 [135. 111. 111.   7.]]
