# Trova la Moneta Falsa

In un numpy array di n elementi (2 < n < 240) ci sono tutte monete di un certo peso ed una leggermente più pesante. Dovete scoprire quale è l'indice della moneta più pesante!
Per farlo dovete costruire una funzione TEST che dati due array confronti le loro somme e restituisca:
- 1 se il primo è più pesante
- 2 se il secondo è più pesante
- 0 se hanno lo stesso peso

Questa funzione è l'unico modo in cui potete accedere agli elementi dell'array ed il vostro obiettivo è scoprire la moneta falsa in meno TEST possibili.

Il programma dovrà generare nel main una serie di numpy array di varie dimensione e ogni elemento inizializzato ad un numero casuale tra 10000 e 20000 e successivamente scgeliere un indice casuale e aggiungere 1 a quell'elemento.
Create poi una matrice contenente:
- Numero di elementi dell'i-esimo array
- Indice della moneta più pesante dell'i-esimo array
- Indice restituito dal vostro algoritmo dell'i-esimo array
- Numero di volte in cui avete usato TEST per l'i-esimo array

La valutazione terrà conto dell'ottimalità e dell'esattezza della soluzione in primo luogo, successivamente dello stile e chiarezza del codice.
Non è ammesso l'utilizzo di liste, tuple o simili, ma solo di array di numpy.
Buon lavoro!

EXTRA BONUS: fatelo nel caso in cui non sapete se la moneta falsa è più pesante o leggera

In [1]:
import numpy as np

In [2]:
def TEST(a,b):
    sa = sum(a)
    sb = sum(b)
    if sa > sb:
        return 1
    elif sa < sb:
        return 2
    return 0   

In [3]:
def search(a,it):
    n = len(a)
    if n == 1:
        arr = np.array([a,it],dtype=object)
        return arr
    third_a = np.array_split(a,3)
    if n%3 == 2 or n%3 == 0:
        big = TEST(third_a[0],third_a[1])
        it +=1
        return search(third_a[big-1],it)
    elif n%3 == 1:
        big = TEST(third_a[1],third_a[2])
        it +=1
        return search(third_a[big],it)

In [7]:
np.random.seed(84) #domanda fondamentale *2
A = np.full((237,4),0)
for n in range(3,240):
    val = np.random.randint(10000, 200001)
    arr = np.ones((n,))
    ind = np.random.randint(0,n)
    arr[ind] = arr[ind] + 1
    coin = search(arr,0)
    my_ind = np.where(arr == coin[0])
    A[n-3][0] = n
    A[n-3][1] = ind
    A[n-3][2] = my_ind[0]
    A[n-3][3] = coin[1]
print(A)

[[  3   1   1   1]
 [  4   0   0   2]
 [  5   4   4   1]
 [  6   5   5   2]
 [  7   1   1   2]
 [  8   2   2   2]
 [  9   1   1   2]
 [ 10   5   5   2]
 [ 11   9   9   2]
 [ 12   8   8   3]
 [ 13   0   0   3]
 [ 14   0   0   3]
 [ 15  14  14   2]
 [ 16   4   4   3]
 [ 17   2   2   3]
 [ 18  15  15   3]
 [ 19  17  17   3]
 [ 20   9   9   3]
 [ 21   1   1   3]
 [ 22   9   9   3]
 [ 23  10  10   3]
 [ 24  15  15   3]
 [ 25  20  20   3]
 [ 26  21  21   3]
 [ 27  11  11   3]
 [ 28  27  27   3]
 [ 29   4   4   3]
 [ 30  17  17   3]
 [ 31  14  14   3]
 [ 32  13  13   3]
 [ 33  13  13   3]
 [ 34   5   5   4]
 [ 35  30  30   3]
 [ 36  10  10   3]
 [ 37  20  20   3]
 [ 38  17  17   3]
 [ 39  29  29   4]
 [ 40  12  12   3]
 [ 41  19  19   4]
 [ 42  18  18   3]
 [ 43   2   2   4]
 [ 44  22  22   4]
 [ 45   4   4   3]
 [ 46  16  16   4]
 [ 47  41  41   3]
 [ 48  46  46   4]
 [ 49   5   5   4]
 [ 50   7   7   4]
 [ 51  13  13   4]
 [ 52   7   7   4]
 [ 53  38  38   4]
 [ 54  24  24   4]
 [ 55   3   