# Trova la Moneta Falsa

In un numpy array di n elementi (2 < n < 240) ci sono tutte monete di un certo peso ed una leggermente più pesante. Dovete scoprire quale è l'indice della moneta più pesante!
Per farlo dovete costruire una funzione TEST che dati due array confronti le loro somme e restituisca:
- 1 se il primo è più pesante
- 2 se il secondo è più pesante
- 0 se hanno lo stesso peso

Questa funzione è l'unico modo in cui potete accedere agli elementi dell'array ed il vostro obiettivo è scoprire la moneta falsa in meno TEST possibili.

Il programma dovrà generare nel main una serie di numpy array di varie dimensione e ogni elemento inizializzato ad un numero casuale tra 10000 e 20000 e successivamente scgeliere un indice casuale e aggiungere 1 a quell'elemento.
Create poi una matrice contenente:
- Numero di elementi dell'i-esimo array
- Indice della moneta più pesante dell'i-esimo array
- Indice restituito dal vostro algoritmo dell'i-esimo array
- Numero di volte in cui avete usato TEST per l'i-esimo array

La valutazione terrà conto dell'ottimalità e dell'esattezza della soluzione in primo luogo, successivamente dello stile e chiarezza del codice.
Non è ammesso l'utilizzo di liste, tuple o simili, ma solo di array di numpy.
Buon lavoro!

EXTRA BONUS: fatelo nel caso in cui non sapete se la moneta falsa è più pesante o leggera

In [1]:
import numpy as np

In [2]:
def TEST(a,b):
    sum_a = sum(a)
    sum_b = sum(b)
    if (sum_a > sum_b):
        return 1 
    elif (sum_a < sum_b):
        return 2
    return 0

In [3]:
def search(arr,it):
    n = len(arr)
    if n == 1:
        return (arr,it)
    third_a = np.array_split(arr,3)
    if n%3 == 2 or n%3 == 0:
        big = TEST(third_a[0],third_a[1])
        it +=1
        return search(third_a[big-1],it)
    elif n%3 == 1:
        big = TEST(third_a[1],third_a[2])
        it +=1
        return search(third_a[big],it)

In [4]:
np.random.seed(98) #domanda fondamentale *2
mat = np.full((237,4),0)
for n in range(3,240):
    val = np.random.randint(10000, 200001)
    arr = val*np.ones((n,))
    ind = np.random.randint(0,n)
    arr[ind] = arr[ind] + 1
    coin = search(arr,0)
    my_ind = np.where(arr == coin[0])
    mat[n-3][0] = n
    A[n-3][1] = ind
    A[n-3][2] = my_ind[0]
    A[n-3][3] = coin[1]
print(A)


[[  3   2   2   1]
 [  4   3   3   1]
 [  5   4   4   1]
 [  6   1   1   2]
 [  7   2   2   2]
 [  8   2   2   2]
 [  9   3   3   2]
 [ 10   7   7   2]
 [ 11   6   6   2]
 [ 12   9   9   3]
 [ 13   6   6   3]
 [ 14   5   5   3]
 [ 15  10  10   3]
 [ 16  10  10   2]
 [ 17  11  11   3]
 [ 18   8   8   3]
 [ 19   3   3   3]
 [ 20   2   2   3]
 [ 21  10  10   3]
 [ 22   7   7   3]
 [ 23  12  12   3]
 [ 24  15  15   3]
 [ 25  24  24   3]
 [ 26  17  17   3]
 [ 27  13  13   3]
 [ 28  11  11   3]
 [ 29  15  15   3]
 [ 30  27  27   3]
 [ 31  25  25   3]
 [ 32  27  27   3]
 [ 33   1   1   4]
 [ 34  12  12   4]
 [ 35   0   0   4]
 [ 36  33  33   4]
 [ 37  35  35   3]
 [ 38  19  19   4]
 [ 39  19  19   4]
 [ 40  32  32   4]
 [ 41  28  28   4]
 [ 42  37  37   3]
 [ 43  41  41   3]
 [ 44  24  24   3]
 [ 45  36  36   4]
 [ 46  45  45   3]
 [ 47   2   2   4]
 [ 48  16  16   4]
 [ 49  39  39   4]
 [ 50  12  12   4]
 [ 51   3   3   4]
 [ 52  32  32   4]
 [ 53  21  21   4]
 [ 54   7   7   4]
 [ 55  44  4