# Trova la Moneta Falsa

In un numpy array di n elementi (2 < n < 240) ci sono tutte monete di un certo peso ed una leggermente più pesante. Dovete scoprire quale è l'indice della moneta più pesante!
Per farlo dovete costruire una funzione TEST che dati due array confronti le loro somme e restituisca:
- 1 se il primo è più pesante
- 2 se il secondo è più pesante
- 0 se hanno lo stesso peso

Questa funzione è l'unico modo in cui potete accedere agli elementi dell'array ed il vostro obiettivo è scoprire la moneta falsa in meno TEST possibili.

In [ ]:
import numpy as np

def TEST(x,y):
    if sum(x)/len(x)>sum(y)/len(y):
        return 1
    elif sum(x)/len(x)<sum(y)/len(y):
        return 2
    return 0

def binary_search(arr, start, end, counter):
    if start == end:
        return [start, counter]
    arr_split = np.split(arr,[int((end-start)/2)+1])
    test = TEST(arr_split[0], arr_split[1])
    counter += 1
    if test == 1:
        return binary_search(arr_split[0], start, start + len(arr_split[0]) - 1, counter)
    if test == 2:
        return binary_search(arr_split[1], end - len(arr_split[1]) + 1, end, counter)

Il programma dovrà generare nel main una serie di numpy array di varie dimensione e ogni elemento inizializzato ad un numero casuale tra 10000 e 20000 e successivamente scgeliere un indice casuale e aggiungere 1 a quell'elemento.
Create poi una matrice contenente:
- Numero di elementi dell'i-esimo array
- Indice della moneta più pesante dell'i-esimo array
- Indice restituito dal vostro algoritmo dell'i-esimo array
- Numero di volte in cui avete usato TEST per l'i-esimo array

In [ ]:
n = 4
dimensions = np.random.randint(2, 241, size = n)
values = np.random.randint(10000, 20001, size = n)
sol_M = np.zeros((n,4))
#Adesso avrei creato una lista e usato un loop per riempirla di array, così da "automatizzare" la costruzione delle purses.
#Non potendo usare liste, inizializzo a mano un numero piccolo di array.

purse_0 = np.full((dimensions[0],1), values[0])
index_0 = np.random.randint(dimensions[0])
purse_0[index_0] += 1
sol_M[0][0] = dimensions[0]
sol_M[0][1] = index_0

sol0 = binary_search(purse_0,0,dimensions[0]-1,0)
sol_M[0][2] = sol0[0]
sol_M[0][3] = sol0[1]


purse_1 = np.full((dimensions[1],1), values[1])
index_1 = np.random.randint(dimensions[1])
purse_1[index_1] += 1
sol_M[1][0] = dimensions[1]
sol_M[1][1] = index_1

sol1 = binary_search(purse_1,0,dimensions[1]-1,0)
sol_M[1][2] = sol1[0]
sol_M[1][3] = sol1[1]


purse_2 = np.full((dimensions[2],1), values[2])
index_2 = np.random.randint(dimensions[2])
purse_2[index_2] += 1
sol_M[2][0] = dimensions[2]
sol_M[2][1] = index_2

sol2 = binary_search(purse_2,0,dimensions[2]-1,0)
sol_M[2][2] = sol2[0]
sol_M[2][3] = sol2[1]


purse_3 = np.full((dimensions[3],1), values[3])
index_3 = np.random.randint(dimensions[3])
purse_3[index_3] += 1
sol_M[3][0] = dimensions[3]
sol_M[3][1] = index_3

sol3 = binary_search(purse_3,0,dimensions[3]-1,0)
sol_M[3][2] = sol3[0]
sol_M[3][3] = sol3[1]

#Con lista di Array:
#purses = []
#indices = []
#for i in range(n):
#   purses.append(np.full((dimensions[i],1), values[i]))
#   indices.append(np.random.randint(dimensions[i]))
#   purses[i][indices[i]] += 1
#  sol_M[i][0] = dimensions[i]
#  sol_M[i][1] = indices[i]

#  sol = binary_search(purses[i],0,dimensions[i]-1,0)
#  sol_M[i][2] = sol[0]
#  sol_M[i][3] = sol[1]

print(sol_M)

[[120.  84.  84.   7.]
 [ 33.  31.  31.   5.]
 [143.  84.  84.   7.]
 [126. 120. 120.   7.]]


La valutazione terrà conto dell'ottimalità e dell'esattezza della soluzione in primo luogo, successivamente dello stile e chiarezza del codice.
Non è ammesso l'utilizzo di liste, tuple o simili, ma solo di array di numpy.
Buon lavoro!

EXTRA BONUS: fatelo nel caso in cui non sapete se la moneta falsa è più pesante o leggera

In [ ]:
#BONUS

import numpy as np

def TEST_bonus(x,y):
    xval = float(sum(x))/float(len(x))
    yval = float(sum(y))/float(len(y))
    if xval.is_integer() == 0:
        return 1
    elif yval.is_integer() == 0:
        return 2
    if len(x) == 1 and len(y) == 1:
        return 0
    if len(x) == 1:
        return 1
    if len(y) == 1:
        return 2

def binary_search_bonus(arr, start, end, counter):
    if start == end:
        return [start, counter, 0]
    arr_split = np.split(arr,[int((end-start)/2)+1])
    test = TEST_bonus(arr_split[0], arr_split[1])
    counter += 1
    if test == 1:
        return binary_search_bonus(arr_split[0], start, start + len(arr_split[0]) - 1, counter)
    if test == 2:
        return binary_search_bonus(arr_split[1], end - len(arr_split[1]) + 1, end, counter)
    if test == 0:
        return [start, counter, 1]

In [ ]:
n = 4
dimensions = np.random.randint(2, 241, size = n)
values = np.random.randint(10000, 20001, size = n)
sol_M = np.zeros((n,4))
purses = []
indices = []

for i in range(n):
    purses.append(np.full((dimensions[i],1), values[i]))
    indices.append(np.random.randint(dimensions[i]))
    if np.random.randint(2):
        purses[i][indices[i]] += 1
    else:
        purses[i][indices[i]] -= 1
    sol_M[i][0] = dimensions[i]
    sol_M[i][1] = indices[i]

    sol = binary_search_bonus(purses[i],0,dimensions[i]-1,0)
    if sol[2]:
        arr_s = np.split(purses[i], [sol[0]+1])
        test = TEST_bonus(arr_s[0], arr_s[1])
        sol[1] += 1
        if test == 2:
            sol[0] += 1
    sol_M[i][2] = sol[0]
    sol_M[i][3] = sol[1]

print(sol_M)

[[ 61.  42.  42.   7.]
 [172. 153. 153.   7.]
 [125.  77.  77.   8.]
 [171.  82.  82.   9.]]
