# Trova la Moneta Falsa

In un numpy array di n elementi (2 < n < 240) ci sono tutte monete di un certo peso ed una leggermente più pesante. Dovete scoprire quale è l'indice della moneta più pesante!
Per farlo dovete costruire una funzione TEST che dati due array confronti le loro somme e restituisca:
- 1 se il primo è più pesante
- 2 se il secondo è più pesante
- 0 se hanno lo stesso peso

Questa funzione è l'unico modo in cui potete accedere agli elementi dell'array ed il vostro obiettivo è scoprire la moneta falsa in meno TEST possibili.

Il programma dovrà generare nel main una serie di numpy array di varie dimensione e ogni elemento inizializzato ad un numero casuale tra 10000 e 20000 e successivamente scgeliere un indice casuale e aggiungere 1 a quell'elemento.
Create poi una matrice contenente:
- Numero di elementi dell'i-esimo array
- Indice della moneta più pesante dell'i-esimo array
- Indice restituito dal vostro algoritmo dell'i-esimo array
- Numero di volte in cui avete usato TEST per l'i-esimo array

La valutazione terrà conto dell'ottimalità e dell'esattezza della soluzione in primo luogo, successivamente dello stile e chiarezza del codice.
Non è ammesso l'utilizzo di liste, tuple o simili, ma solo di array di numpy.
Buon lavoro!

EXTRA BONUS: fatelo nel caso in cui non sapete se la moneta falsa è più pesante o leggera

In [1]:
import numpy as np
from random import * 

In [7]:
# Funzione test richiesta
def test(ar1,ar2):
    if (ar1.sum(axis=0)>ar2.sum(axis=0)):
        return 1
    elif (ar1.sum(axis=0)<ar2.sum(axis=0)):
        return 2
    else: return 0
    

def trova_moneta(arr):
    count=0                  # contatore che conta quante volte uso la funzione test
    index=0                  # indice della moneta più pesante
    size=arr.shape[0]
    while (size!=1):
        size=arr.shape[0]
        if (test(arr[0:arr.shape[0]//2],arr[arr.shape[0]//2:arr.shape[0]//2*2])==1):
            #print('test==1')
            count=count+1
            index=index+0
            arr=arr[0:arr.shape[0]//2]
        if (test(arr[0:arr.shape[0]//2],arr[arr.shape[0]//2:arr.shape[0]//2*2])==2 and arr.shape[0]!=1):
            #print('test==2')
            count=count+1
            index=index+arr.shape[0]//2
            arr=arr[arr.shape[0]//2:arr.shape[0]//2*2]
        if (test(arr[0:arr.shape[0]//2],arr[arr.shape[0]//2:arr.shape[0]//2*2])==0 and arr.shape[0]!=1):
            #print('test==0')
            count=count+1
            index=index+arr.shape[0]-1
            size=1
    return index,count



#np.random.seed(42)

# Funzione che crea l'array
def vettore():
    size=np.random.randint(2,240)                          # dimensione del vettore
    arr=np.array([np.random.randint(10000,20000)]*size)    # creo il vettore
    index=np.random.randint(0,size)                        # scelgo l'indice della moneta più pesante
    arr[index]=arr[index]+1                                # aggiorno il vettore
    return size, index, arr
    

N=30                                                         # Numero di vettori che voglio
M=np.zeros((N,4))

# Creo la matrice    
for i in range(N):
    M[i][0],M[i][1],arr=vettore()
    #print(arr)
    M[i][2],M[i][3]=trova_moneta(arr)
        
    
print(M)
    
    
        
        
    

[[ 47.  24.  24.   5.]
 [ 76.  64.  64.   6.]
 [124. 113. 113.   6.]
 [196. 116. 116.   7.]
 [ 43.  22.  22.   5.]
 [ 59.  39.  39.   5.]
 [126.  12.  12.   6.]
 [ 80.  10.  10.   6.]
 [ 34.  33.  33.   2.]
 [ 55.   7.   7.   5.]
 [211. 129. 129.   7.]
 [126.  98.  98.   6.]
 [129. 118. 118.   7.]
 [155.  21.  21.   7.]
 [ 99.  56.  56.   6.]
 [222.  72.  72.   7.]
 [225. 103. 103.   7.]
 [ 68.  51.  51.   6.]
 [152.  83.  83.   7.]
 [ 28.  10.  10.   4.]
 [ 45.  33.  33.   5.]
 [ 12.   6.   6.   3.]
 [ 48.  29.  29.   5.]
 [160.  82.  82.   7.]
 [106. 103. 103.   6.]
 [221.  79.  79.   7.]
 [ 85.  24.  24.   6.]
 [ 20.   6.   6.   4.]
 [ 51.  29.  29.   5.]
 [ 29.  11.  11.   4.]]
