# Trova la Moneta Falsa

In un numpy array di n elementi (2 < n < 240) ci sono tutte monete di un certo peso ed una leggermente più pesante. Dovete scoprire quale è l'indice della moneta più pesante!
Per farlo dovete costruire una funzione TEST che dati due array confronti le loro somme e restituisca:
- 1 se il primo è più pesante
- 2 se il secondo è più pesante
- 0 se hanno lo stesso peso

Questa funzione è l'unico modo in cui potete accedere agli elementi dell'array ed il vostro obiettivo è scoprire la moneta falsa in meno TEST possibili.

Il programma dovrà generare nel main una serie di numpy array di varie dimensione e ogni elemento inizializzato ad un numero casuale tra 10000 e 20000 e successivamente scgeliere un indice casuale e aggiungere 1 a quell'elemento.
Create poi una matrice contenente:
- Numero di elementi dell'i-esimo array
- Indice della moneta più pesante dell'i-esimo array
- Indice restituito dal vostro algoritmo dell'i-esimo array
- Numero di volte in cui avete usato TEST per l'i-esimo array

La valutazione terrà conto dell'ottimalità e dell'esattezza della soluzione in primo luogo, successivamente dello stile e chiarezza del codice.
Non è ammesso l'utilizzo di liste, tuple o simili, ma solo di array di numpy.
Buon lavoro!

EXTRA BONUS: fatelo nel caso in cui non sapete se la moneta falsa è più pesante o leggera

In [1]:
import numpy as np

big_N = 150 # numero di array da testare

def TEST(arr1, arr2):
    sum1 = np.sum(arr1)
    sum2 = np.sum(arr2)
    if sum1 > sum2:
        return 1
    if sum2 > sum1:
        return 2
    return 0
    
def initialize():
    k = 10000 + np.random.randint(10001)
    n = 3 + np.random.randint(237)
    coinarray = np.zeros(n+2, dtype = np.int) + k
    fake = np.random.randint(n)
    coinarray[fake] += 1
    coinarray[n] = n
    coinarray[n+1] = fake
    return coinarray

def fakeindexfinder(arr, n):
    if n == 1:
        return np.array([0, 0])
    half = int(n/2)
    result = TEST(arr[:half], arr[half:2*half])
    if result == 0:
        return np.array([n-1, 1])
    if result == 1:
        return fakeindexfinder(arr[:half], half) + np.array([0, 1])
    return fakeindexfinder(arr[half:], half) + np.array([half, 1])

matsize = np.array([big_N, 4])
checkmatrix = np.zeros(matsize)

i = 0
while i < big_N:
    data = initialize()
    coinarray = data[:-2]
    n = data[-2] # Se n (lunghezza dell'i-esimo array) è accessibile senza TEST, altrimenti:
    TEST_count = 0
    #checker = False
    #n = 1
    #while not checker:
    #    try:
    #        TEST_count += 1
    #        TEST(coinarray[:n], coinarray[n])
    #        n += 1
    #    except:
    #        checker = True
    checkmatrix[i] = np.concatenate((np.array([n, data[-1]]), fakeindexfinder(coinarray, n) + np.array([0, TEST_count])))
    
    i += 1
    
print(checkmatrix)

[[152. 142. 142.   7.]
 [132.  61.  61.   7.]
 [ 26.   9.   9.   4.]
 [189.  16.  16.   7.]
 [ 46.  45.  45.   2.]
 [ 21.   2.   2.   4.]
 [ 13.   5.   5.   3.]
 [190.  67.  67.   6.]
 [ 81.   0.   0.   6.]
 [136.  11.  11.   7.]
 [ 31.  20.  20.   4.]
 [238. 109. 109.   7.]
 [139.  65.  65.   7.]
 [ 91.  49.  49.   5.]
 [140.  22.  22.   7.]
 [233. 137. 137.   7.]
 [166.  36.  36.   7.]
 [152. 103. 103.   5.]
 [ 65.  26.  26.   6.]
 [ 44.  22.  22.   5.]
 [222.  29.  29.   7.]
 [232. 110. 110.   7.]
 [212.  89.  89.   7.]
 [119. 110. 110.   6.]
 [ 24.  20.  20.   4.]
 [214.  60.  60.   7.]
 [222. 210. 210.   7.]
 [ 92.  11.  11.   6.]
 [ 50.   4.   4.   5.]
 [190.  53.  53.   7.]
 [149. 116. 116.   7.]
 [ 33.  19.  19.   5.]
 [ 31.  18.  18.   4.]
 [237.  39.  39.   7.]
 [ 31.   3.   3.   4.]
 [220. 106. 106.   7.]
 [233.   5.   5.   7.]
 [ 20.   8.   8.   4.]
 [ 12.   8.   8.   3.]
 [211.   0.   0.   7.]
 [ 87.  69.  69.   6.]
 [ 73.  60.  60.   6.]
 [132. 106. 106.   7.]
 [ 79.  60.