# Trova la Moneta Falsa

In un numpy array di n elementi (2 < n < 240) ci sono tutte monete di un certo peso ed una leggermente più pesante. Dovete scoprire quale è l'indice della moneta più pesante!
Per farlo dovete costruire una funzione TEST che dati due array confronti le loro somme e restituisca:
- 1 se il primo è più pesante
- 2 se il secondo è più pesante
- 0 se hanno lo stesso peso

Questa funzione è l'unico modo in cui potete accedere agli elementi dell'array ed il vostro obiettivo è scoprire la moneta falsa in meno TEST possibili.

Il programma dovrà generare nel main una serie di numpy array di varie dimensione e ogni elemento inizializzato ad un numero casuale tra 10000 e 20000 e successivamente scgeliere un indice casuale e aggiungere 1 a quell'elemento.
Create poi una matrice contenente:
- Numero di elementi dell'i-esimo array
- Indice della moneta più pesante dell'i-esimo array
- Indice restituito dal vostro algoritmo dell'i-esimo array
- Numero di volte in cui avete usato TEST per l'i-esimo array

La valutazione terrà conto dell'ottimalità e dell'esattezza della soluzione in primo luogo, successivamente dello stile e chiarezza del codice.
Non è ammesso l'utilizzo di liste, tuple o simili, ma solo di array di numpy.
Buon lavoro!

In [1]:
import numpy as np

In [ ]:
# non funziona al 100%, 

In [329]:
def test(arr1,arr2):
    if np.sum(arr1)>np.sum(arr2):
        return 1
    elif np.sum(arr2)>np.sum(arr1):
        return 2
    else:
        return 0

In [385]:
def indicemoneta(x,cost):
    k=0
    while (len(x))>1:
        n=len(x) // 2
        part1 = x[:n]
        part2 = x[n : 2 * n]
        result = test(part1, part2)
        cost=cost+1
        if result == 1:
            x = part1
        elif result == 2:
            x = part2
            k=k+len(x)
        elif result == 0:
            vector = x[2 * n :]
            x=vector
            k=k+n
    return k,cost

    

In [339]:
def create_coins(x,xnew):
    coins=np.zeros(x.shape[0], dtype=np.int32)
    for i in range(len(x)):
        if x[i]!=xnew[i]:
            coins[i]=1
    return coins

In [386]:
print ('inserire numero di array richiesto')
howmanyarray=int(input())
matrix=np.full((howmanyarray,4), 0)
#ho matrice con una dimensione random di righe e come colonne il numero di array stabilito da me
for i in range(howmanyarray):
    x=np.random.randint((10000), size=(np.random.randint(2,240),1), dtype=np.int32)+10000
    indice_moneta=np.random.randint(x.shape[0])
    xnew=np.copy(x)
    xnew[indice_moneta]=x[indice_moneta]+1
    coins=create_coins(x,xnew)
    cost=0
    idx,c=indicemoneta(coins,cost)
    matrix[i][2]=idx #indice algoritmo
    matrix[i][0]=x.shape[0] #number elements in array
    matrix[i][1]=indice_moneta #indice moneta
    matrix[i][3]=c
matrix

inserire numero di array richiesto
10


array([[130,  59,  59,   7],
       [221, 110, 110,   7],
       [107,  60,  60,   6],
       [ 33,  31,  31,   5],
       [ 50,   5,   4,   5],
       [134,  19,  19,   7],
       [ 38,  28,  28,   5],
       [122,  57,  56,   6],
       [ 40,  23,  23,   5],
       [210,  92,  92,   7]])

In [351]:
x=np.random.randint((10000), size=(np.random.randint(2,240),1), dtype=np.int32)+10000
indice_moneta=np.random.randint(x.shape[0])
xnew=np.copy(x)
xnew[indice_moneta]=x[indice_moneta]+1
coins=create_coins(x,xnew)
coins

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [353]:
n=len(coins) // 2
part1 = coins[:n]
part1

array([0, 1, 0, 0, 0])

In [354]:
part2 = coins[n : 2 * n]
part2


array([0, 0, 0, 0, 0])

In [356]:
part3=coins[2 * n :]
len(part3)

1

In [362]:
v=np.array([0,0,0,1,0,0,0,0,0])
print(v[:4])

[0 0 0 1]


EXTRA BONUS: fatelo nel caso in cui non sapete se la moneta falsa è più pesante o leggera