# Trova la Moneta Falsa

In un numpy array di n elementi (2 < n < 240) ci sono tutte monete di un certo peso ed una leggermente più pesante. Dovete scoprire quale è l'indice della moneta più pesante!
Per farlo dovete costruire una funzione TEST che dati due array confronti le loro somme e restituisca:
- 1 se il primo è più pesante
- 2 se il secondo è più pesante
- 0 se hanno lo stesso peso

Questa funzione è l'unico modo in cui potete accedere agli elementi dell'array ed il vostro obiettivo è scoprire la moneta falsa in meno TEST possibili.

Il programma dovrà generare nel main una serie di numpy array di varie dimensione e ogni elemento inizializzato ad un numero casuale tra 10000 e 20000 e successivamente scgeliere un indice casuale e aggiungere 1 a quell'elemento.
Create poi una matrice contenente:
- Numero di elementi dell'i-esimo array
- Indice della moneta più pesante dell'i-esimo array
- Indice restituito dal vostro algoritmo dell'i-esimo array
- Numero di volte in cui avete usato TEST per l'i-esimo array

La valutazione terrà conto dell'ottimalità e dell'esattezza della soluzione in primo luogo, successivamente dello stile e chiarezza del codice.
Non è ammesso l'utilizzo di liste, tuple o simili, ma solo di array di numpy.
Buon lavoro!

EXTRA BONUS: fatelo nel caso in cui non sapete se la moneta falsa è più pesante o leggera

In [2]:
import numpy as np

In [3]:
def com_pair(a1, a2):
    s1=np.sum(a1)
    s2=np.sum(a2)
    return 1*int(s1>s2)+2*int(s2>s1)

In [4]:
def find_heavycoin(a,n):
    ind=0
    nt=0
    while(len(a)!=1):
        a1=a[:int(len(a)/2)]
        a2=a[-int(len(a)/2):]
        res=com_pair(a1,a2)
        nt+=1
        if res==0:
            return ind+int(len(a)/2),nt
        elif res==1:
            a=a1
        else:
            ind+=(int(len(a)/2)+len(a)%2)
            a=a2
    return ind,nt  

m = 100 # n di array che vogliamo considerare
mat = np.zeros((m,4))

for i in range(0,m):
    n = np.random.randint(2,241)
    arr = np.random.randint(10000,20001)*np.ones(n)
    heavy_ind = np.random.randint(0,n)
    arr[heavy_ind] += 1
    sol, ntest = find_heavycoin(arr,n);
    mat[i,0]=n
    mat[i,1]=heavy_ind
    mat[i,2]=sol
    mat[i,3]=ntest
    
print(mat)
    


[[166.  50.  50.   7.]
 [219.  20.  20.   5.]
 [178. 129. 129.   7.]
 [160.  85.  85.   7.]
 [117.  77.  77.   5.]
 [ 70.  29.  29.   6.]
 [111.  19.  19.   6.]
 [ 74.  30.  30.   6.]
 [112.  79.  79.   6.]
 [ 19.   3.   3.   4.]
 [217. 185. 185.   7.]
 [ 86.  67.  67.   5.]
 [ 94.   5.   5.   4.]
 [134. 116. 116.   7.]
 [ 85.  68.  68.   6.]
 [109.  42.  42.   6.]
 [ 77.   5.   5.   6.]
 [216. 202. 202.   4.]
 [218. 170. 170.   5.]
 [102.  63.  63.   3.]
 [157.  56.  56.   7.]
 [ 63.  55.  55.   3.]
 [212.  24.  24.   7.]
 [ 35.   8.   8.   2.]
 [198.  93.  93.   7.]
 [240. 134. 134.   7.]
 [137.  59.  59.   4.]
 [150. 112. 112.   2.]
 [115.  77.  77.   6.]
 [ 55.   4.   4.   5.]
 [ 86.  12.  12.   6.]
 [106.  93.  93.   6.]
 [ 83.  23.  23.   5.]
 [ 89.  41.  41.   5.]
 [ 80.  17.  17.   5.]
 [ 91.   0.   0.   6.]
 [222. 149. 149.   7.]
 [ 38.   5.   5.   5.]
 [124. 103. 103.   6.]
 [168.  79.  79.   7.]
 [136.  30.  30.   7.]
 [ 63.  11.  11.   4.]
 [161.  45.  45.   7.]
 [167. 134.