# Successione di Fibonacci
Stampa i primi n numeri della successione di Fibonacci.

In [10]:
n = 10
def fibo(n):
    if(n <= 2):
        return 1
    else:
        a=1
        b=1
        for i in range(3,n+1):
            c=a+b
            a=b
            b=c
        return c
print("0")
for i in range(1,n):
    print(fibo(i))



0
1
1
2
3
5
8
13
21
34


# Un'altra successione
Scrivere i primi n elementi ($a_n$) di una successione così definita: 
- i primi tre elementi valgono 1, 7, 18.
- i successivi (i>=4) valgono 
$a_n = a_{n-1} + a_{n-3} - a_{n-2} + 2$


Esempio: 1 7 18 14 5 11 22 18 9 15 26 22 13 19 30 


In [4]:
import numpy as np
n=15
v=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
v[0]=1
v[1]=7
v[2]=18
for i in range (3,15):
    v[i]=v[i-1]+v[i-3]-v[i-2]+2
for i in range (0,15):
    print(v[i])

1
7
18
14
5
11
22
18
9
15
26
22
13
19
30


# Triangolo di Tartaglia
Scrivere le prime n righe del triangolo di Tartaglia 

In [5]:
import numpy as np
n=10
nn=n+1
a=np.zeros((nn,nn))
a[0][0]=1
for j in range (1,nn):
    a[0][j]=0
for i in range (1,nn):
    a[i][0]=1
    for k in range (1,nn):
        a[i][k]=a[i-1][k-1]+a[i-1][k]
print(a)        



[[  1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  1.   1.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  1.   2.   1.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  1.   3.   3.   1.   0.   0.   0.   0.   0.   0.   0.]
 [  1.   4.   6.   4.   1.   0.   0.   0.   0.   0.   0.]
 [  1.   5.  10.  10.   5.   1.   0.   0.   0.   0.   0.]
 [  1.   6.  15.  20.  15.   6.   1.   0.   0.   0.   0.]
 [  1.   7.  21.  35.  35.  21.   7.   1.   0.   0.   0.]
 [  1.   8.  28.  56.  70.  56.  28.   8.   1.   0.   0.]
 [  1.   9.  36.  84. 126. 126.  84.  36.   9.   1.   0.]
 [  1.  10.  45. 120. 210. 252. 210. 120.  45.  10.   1.]]
